//
//
global using static gpp.GppGlobal;
namespace gpp;


public enum SymbolType
{
  Nonterminal,
  Content,
  Noise,
  End,
  GroupStart,
  GroupEnd,
  LEGACYCommentLine,
  Error,
}

internal enum LRActionType
{
  Shift = 1,
  Reduce = 2,
  Goto = 3,   //TODO  В парсере не используется. В бюлдере буквально раз..
  Accept = 4,
  Error = 5,
}


public enum GroupAdvanceMode
{
  Token,
  Character,
}

public enum GroupEndingMode
{
  Open,
  Closed,
}


public enum EGTProperty
{
  Name,
  Version,
  Author,
  About,
  CharacterSet,
  CharacterMapping,
  GeneratedBy,
  GeneratedDate,
}
//
public static class PropertyExtension
{
  // используется в BuilderPropertyId
  public const int EGTProperty_MaxConst = (int)EGTProperty.GeneratedDate;
  public static int EGTProperty_Max     => EGTProperty_MaxConst;
  public static int EGTProperty_Unknown => -1;

  public static string GetPropertyName(this EGTProperty property_)
  {
    
    switch (property_)
    { 
      case EGTProperty.Name:              return "Name";
      case EGTProperty.Version:           return "Version"; 
      case EGTProperty.Author:            return "Author";
      case EGTProperty.About:             return "About";
      case EGTProperty.CharacterSet:      return "Character Set";
      case EGTProperty.CharacterMapping:  return "Character Mapping";
      case EGTProperty.GeneratedBy:       return "Generated By";
      case EGTProperty.GeneratedDate:     return "Generated Date";
      default:
        { 
          throw new NotImplementedException();
        }
    }
  }
}


internal static class GppGlobal
{
  public static class GOLDParserInfo
  { 
    public const string ProgramName        = "GOLD Parser";
    public const string ProgramVersionText = "5.2.0";
    public const string Author             = "Devin Cook, http://www.goldparser.org";
    public const string Contributor        = "@IntUnsigned";
    public const string Logo               = $"{ProgramName} v{ProgramVersionText}, (c) {Author}, (reconstructed by {Contributor})";
  }

  public const string s_GOLD_Parser_Tables_v1_0 = "GOLD Parser Tables/v1.0";
  public const string s_GOLD_Parser_Tables_v5_0 = "GOLD Parser Tables/v5.0";  
}

internal static class BuilderError
{
  public static Exception Internal(string message_)
  { 
    return new Exception(message_);
  }
}